window.config = {
	WARNING1: 'DO NOT EDIT THIS FILE.  RESERVED FOR SERVER DEFINED ENDPOINT OVERRIDES.',

	env: {
		Env: '@LOCAL|DEMO|UAT|PROD@',
		Product: '@BACKOFFICE@',
		Version: '@VERSION@',
		Customer: '@CUSTOMER@'
	},
	domain: {
		url: '@DOMAIN@',
		endpoints: {
			api: '@API@',
			backoffice: '@BACKOFFICE@',
			trader: '@TRADER@',
			sso: '@SSO@'
		}
	},
	node: {
		url: '@NODE@',
		endpoints: {
			nodepath: {pathname: '@PATH@'}
		}
	},
	cdn: {
		url: '@CDN@',
		endpoints: {
			i18n: '@I18N@'
		}
	},
	s3: {
		url: '@S3_REGION_URL@',
		endpoints: {
			bucketName: '@S3_BUCKET_NAME@'
		}
	},
	punter: {
		url: '@PUNTER_URL@',
		endpoints: {
			bucketName: '@PUNTER_BUCKET_NAME@'
		}
	},
	"agent": {
		"url": "@AGENT@",
		"endpoints": {
			"agentDomain": "@AGENTDOMAIN@"
		}
	},
	"mtn": {
		"url": "@MTN@",
		"endpoints": {
			"mtnDomain": "@MTNDOMAIN@"
		}
	}
}
